README.md

Docs: update readme links

---

consensus/parlia/ramanujanfork.go
consensus/parlia/utils.go
go.mod
go.sum
params/chainspecs/bsc.json

Support BEP-172: Network Stability Enhancement On Slash Occur

Support bep-172: Network Stability Enhancement On Slash Occur BEP-172

---

consensus/parlia/abi.go
consensus/parlia/lubanFork.go
consensus/parlia/parlia.go
consensus/parlia/snapshot.go
core/systemcontracts/upgrade.go
core/vm/contracts.go
core/vm/evm.go
go.mod
go.sum
params/chainspecs/chapel.json
turbo/stages/headerdownload/header_algos.go

upgrade: rename hardfork to Luban & Plato

upgrade: rename hardfork to Luban & Plato

---

turbo/stages/headerdownload/header_algos.go

Fix headersPOW error

---

go.mod
go.sum

Use latest bsc-erigon-lib version

Use latest bsc-erigon-lib version

---

.github/workflows/docker-release.yml
Dockerfile

update docker image and docker file

update docker image

---

go.mod
go.sum

Use latest bsc-erigon version

---

consensus/parlia/parlia.go

Fix getCurrentValidators issue

Fix getCurrentValidators issue

---

README.md

See more: https://github.com/node-real/bsc-erigon/issues/56

 update the hardware requirement for BSC Archive node

---

consensus/parlia/parlia.go

Remove snapshot lock logic

---

cmd/sentinel/sentinel/service/service.go

fix: Resolve deadlock

---

turbo/stages/headerdownload/header_algos.go

Update request length

---

.github/workflows/release.yml
.goreleaser.yml
Makefile
go.mod
go.sum

Update release workflow.
Update prysmaticlabs/gohashtree and btcsuite/btcd

Update release workflow

---

cmd/rpcdaemon/commands/call_traces_test.go
cmd/rpcdaemon/commands/trace_api.go
cmd/rpcdaemon/commands/trace_filtering.go

Fix trace filter
See more https://github.com/node-real/bsc-erigon/issues/106

Fix trace filter

---

turbo/stages/headerdownload/header_algos.go

Update the stride for the first initialCycle

Update the stride for the first initialCycle

---

eth/stagedsync/stage_headers.go
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

Update the way to sync step by step, which can support both step-by-step sync and sync upper-bound set

feature: Step by step sync

---

turbo/stages/headerdownload/header_algos.go

Optimize the downloader process:
1. Increase more about the request stride for faster sync
2. Record the bad link for pow(bsc) scenario

fix: optimization

---

core/state/history_test.go
core/state/historyv2read/history.go
core/state/plain_readonly.go
core/system_contract_lookup.go

This pr fixed two problems:
1. System contract upgrade issue, which cause by didn't update the contract lookup dictionary
2. RPC refine, picked from https://github.com/node-real/bsc-erigon/commit/358af62de2e5a69b8f4d13bea41998110d8d0f28

System contract upgrade fix and RPC refine

---

params/chainspecs/chapel.json

update the hertz hardfork height

update the config

---

go.mod
go.sum

import bsc mainnet updated torrent snapshots https://github.com/node-real/bsc-erigon-snapshot/commit/4eb1c8d660f8edc9cd2e0a4e722958eec32fd79b

update: import bsc mainnet updated torrent snapshots

---

params/version.go

bump version of bsc-erigon of v1.1.4

fix: bump version of bsc-erigon

---

turbo/stages/headerdownload/header_algos.go

Update the local TX if there's only case of fast finality fork but not traditional tx compare

fix: update reorg logic

---

go.mod
go.sum
turbo/stages/headerdownload/header_algos.go
turbo/stages/headerdownload/header_data_struct.go

fix get the highest header error
https://github.com/node-real/bsc-erigon/issues/182

fix reorg logic

---

core/genesis_write.go
eth/backend.go

Fix the genesis hash = nil

---

core/systemcontracts/upgrade.go
eth/backend.go

Fix: https://github.com/node-real/bsc-erigon/issues/282

route by chainName instead of genesis hash.

---

consensus/parlia/parlia.go
params/version.go

bump version and bug fix for system contract

bump version and bug fix for system contract

---

cmd/erigon-el-mock/server.go
cmd/erigon-el/eth1/execution.go
cmd/evm/internal/t8ntool/gen_stenv.go
params/chainspecs/bsc.json
params/version.go
turbo/stages/sentry_mock_test.go
turbo/stages/stageloop.go

Support Feynman && FeynmanFix HF in bsc.

final bsc main net feynman && feynmanFix

---

node/nodecfg/defaults.go
params/chainspecs/bsc.json
params/version.go

1. support feynman && feynmanFix
2. default use eth68

Devel1.2 feynman

---

core/data_availability.go
core/types/block.go
erigon-lib/chain/chain_config.go

more check for validity of sidecars

Cancun bugfix

---

params/chainspecs/chapel.json

[final ](config: setup Testnet Tycho(Cancun) hardfork date)

config: setup Testnet Tycho(Cancun) hardfork date

---

cmd/state/commands/opcode_tracer.go
cmd/state/exec3/calltracer_v3.go
core/system_contract_lookup.go
core/vm/logger.go
erigon-lib/chain/chain_config.go
eth/calltracer/calltracer.go
eth/tracers/js/goja.go
eth/tracers/logger/access_list_tracer.go
eth/tracers/logger/json_stream.go
eth/tracers/logger/logger.go
eth/tracers/logger/logger_json.go
eth/tracers/native/call.go
eth/tracers/native/mux.go
eth/tracers/native/noop.go
eth/tracers/native/prestate.go
polygon/tracer/trace_bor_state_sync_txn.go
turbo/jsonrpc/otterscan_default_tracer.go
turbo/jsonrpc/trace_adhoc.go
turbo/jsonrpc/tracing.go
turbo/transactions/tracing.go

- fix system tx gasused #367 
- remove bsc checkcompatible

Fix system tx gasused

---

params/version.go

bump version

---

core/types/block.go

Withdrawshash is emptyroothash, the withdraws should not be nil

fix withdraw check

---

.github/workflows/check.yml
.github/workflows/ci.yml
.github/workflows/coverage.yml
.github/workflows/qa-clean-exit-block-downloading.yml
.github/workflows/qa-clean-exit-snapshot-downloading.yml
.github/workflows/test-integration.yml
Makefile
params/version.go

- v1.2.7 will be a maintenance release 
- branch rename

bump version and branch rename

---

p2p/sentry/sentry_multi_client/broadcast.go
p2p/sentry/sentry_multi_client/sentry_multi_client.go
turbo/rpchelper/helper.go
turbo/stages/bodydownload/body_algos.go
turbo/stages/bodydownload/body_data_struct.go

1. add some logs
2. fix nil pointer issue
3. optimize body_algos

Nil pointer fix

---

consensus/parlia/snapshot.go

After Bohr it may not set snapshots

Fix set wrong snapshots.

---

cmd/integration/commands/stages.go
core/blob_storage/blob_db.go
eth/backend.go
eth/ethconfig/config.go
eth/ethconsensusconfig/config.go
eth/stagedsync/default_stages.go
eth/stagedsync/stage_bodies.go
turbo/app/snapshots_cmd.go
turbo/cli/flags.go
turbo/services/interfaces.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/bsc_snapshots.go

Erigon3 support blob prune

---

core/blob_storage/blob_db.go
core/snaptype/bsc_types.go
core/types/blob_tx_wrapper.go
core/vm/lightclient/v1/ics23_proof.go
core/vm/lightclient/v1/types.go
eth/ethconsensusconfig/config.go
eth/protocols/eth/protocol_test.go
eth/stagedsync/stage_bodies.go
turbo/app/snapshots_cmd.go
turbo/cli/default_flags.go
turbo/cli/flags.go
turbo/services/interfaces.go

1. fix go lint 
2. fix blob prune issue

Fix blob prune issue

---

cmd/rpcdaemon/cli/config.go
consensus/parlia/parlia.go
turbo/jsonrpc/bsc_api.go
turbo/jsonrpc/daemon.go
turbo/rpchelper/helper.go
turbo/rpchelper/rpc_block.go

eth_getFinalizeHeader/Block

---

consensus/parlia/parlia.go
turbo/jsonrpc/bsc_api.go
turbo/jsonrpc/daemon.go

Finalized header block

---

params/version.go

prepare release v1.2.16

---

consensus/parlia/parlia.go

fix case when execute fail, the finalize block should not be set.

fix finalize

---

consensus/parlia/util.go

Useless logs, so lower the log level

Useless log

---

consensus/parlia/parlia.go
core/blockchain.go
core/state_transition.go

support trace system tx

---

core/state_transition.go

Erigon2 fix

---

turbo/jsonrpc/bsc_api.go

refer to: https://github.com/bnb-chain/bsc/pull/2844

support GetFinalizedBlock by common ratio validators

---

turbo/jsonrpc/eth_api.go
turbo/jsonrpc/eth_call.go
turbo/jsonrpc/eth_call_test.go
turbo/snapshotsync/freezeblocks/bsc_snapshots.go

cherry-pick from https://github.com/erigontech/erigon/pull/13090

Estimate gas

---

core/state_transition.go

add blackList

---

core/rawdb/accessors_chain.go

accessors_chain.go: fix log

---

erigon-lib/downloader/webseed.go

Reverts node-real/bsc-erigon#621

Revert "StageSnapshot struck: fix "no metadata yet""

---

eth/gasprice/feehistory.go
eth/gasprice/gasprice.go
turbo/jsonrpc/eth_receipts.go
turbo/jsonrpc/eth_system.go
turbo/jsonrpc/receipts/receipts_generator.go

Pick from https://github.com/erigontech/erigon/pull/14135.

receipts_generator.go: use WithCustomReadTxNumFunc

---

.github/workflows/test-hive-eest.yml
.github/workflows/test-hive.yml
.github/workflows/test-kurtosis-assertoor.yml
cl/sentinel/sentinel_gossip_test.go
eth/backend.go
eth/stagedsync/exec3.go

1. fix logs
2. fix ci
3. fix the #673

backend.go:  don't run pos downloader or engine api for parlia

---

cmd/downloader/main.go

fix mainfest cmd: add accessor file and remove duplicate txt file.

downloader/main.go: add accessor

---

core/blob_storage/blob_db.go
core/state_transition.go
erigon-lib/chain/snapcfg/util.go
turbo/snapshotsync/freezeblocks/block_snapshots.go
turbo/snapshotsync/freezeblocks/bsc_snapshots.go
turbo/stages/headerdownload/header_algos.go

1. adjust merge limit from 100_000 to 500_000
2. bsc_snapshots have same prune merge logic with blocksnapshots
3. adjust RequestSkeleton stride

Adjust merge limit

---

turbo/snapshotsync/freezeblocks/block_snapshots.go
txnprovider/txpool/pool.go

snapcfg.KnownCfg take too much time in block retire.

Optimize block retire

---

turbo/jsonrpc/eth_receipts.go

fix #759 ,  when use fromblock = `latest`,  ` uint64(fromBlock) > latest` always true, it will return nil.

eth_receipts: fix eth_getLogs

---

core/state/intra_block_state.go

Add accessList nil check for intra_block_state

intra_block_state.go: fix nil pointer dereference
