cmd/sentry/sentry/sentry_grpc_server.go, eth/protocols/eth/protocol.go
bsc `eth67` protocol had been changed to be different from `eth`, it has one more round of handshake.
=> feat: upgrade eth67 handshake msg to be compatible with bsc

README.md
Currently the installation instr4uctions point to the **stable** branch of the bsc-erigon repository on the **ledgerwatch** github.
Updated README.md to point to the correct node-real github bsc-erigon repository and devel branch.
=> Updated getting started section to point to correct github repositories

turbo/stages/headerdownload/header_algos.go
There're frequent logs such as "no block write..", after debugging, find that if strides is too large, some peers are unable to response, so decrease the stride and length to improve the stability of sentry p2p
=> Optimize the sentry p2p stability

cmd/sentry/sentry/sentry_api.go, turbo/stages/headerdownload/header_algos.go
Update the request packet parameter to better match bsc-geth p2p
=> Update the request packet parameter to better match bsc-geth p2p

consensus/parlia/parlia.go, consensus/parlia/snapshot.go
As its show in this [issue](https://github.com/node-real/bsc-erigon/issues/85),  it leads to much more complexity, because of recursive call. 
See more info in [this](https://github.com/bnb-chain/bsc/pull/1514)
=> fix: simplify update of attestation

params/chainspecs/bsc.json
BSC mainnet hard fork Luban will be enabled on 12th June, detail refer: https://github.com/bnb-chain/bsc/releases/tag/v1.2.4
=> upgrade: update luban fork height on BSC mainnet

consensus/parlia/parlia.go, consensus/parlia/snapshot.go, core/types/vote.go
just refer: https://github.com/bnb-chain/bsc/pull/1651
=> fix: remove naturally finality

go.mod, go.sum
It fixes issue:[Fail to sync from genesis block](https://github.com/node-real/bsc-erigon/issues/94)
The fix is in another repo: https://github.com/node-real/bsc-erigon-lib/pull/11
Here is the code, will hit `evm.chainRules.IsIstanbul:` at early blocks, need to make IsParlia to use the right precompiles.
```
func (evm *EVM) precompile(addr libcommon.Address) (PrecompiledContract, bool) {
var precompiles map[libcommon.Address]PrecompiledContract
switch {
case evm.chainRules.IsPlato:
precompiles = PrecompiledContractsPlato
case evm.chainRules.IsLuban:
precompiles = PrecompiledContractsLuban
case evm.chainRules.IsPlanck:
precompiles = PrecompiledContractsPlanck
case evm.chainRules.IsMoran:
precompiles = PrecompiledContractsIsMoran
case evm.chainRules.IsNano:
precompiles = …
```
=> fix: sync from genesis

consensus/parlia/lubanFork.go, consensus/parlia/parlia.go
This pr is to solve same issue of https://github.com/node-real/bsc-erigon/pull/54, to make sure getCurrentValidators are always valid even after reboot.
=> fix: Update the way to get currentValidators

go.mod, go.sum
Import updated bsc-erigon bittorrent snapshots of https://github.com/node-real/bsc-erigon-snapshot/commit/e2aea6f08f5a8f6ca459162d76a5dcfb521ecd95
=> update: Import updated bsc-erigon bittorrent snapshots

turbo/stages/headerdownload/header_algos.go
According to https://github.com/node-real/bsc-erigon/blob/devel/turbo/stages/headerdownload/header_algos.go#L461-L462
When headerDownloader update its status, it assume the req is in reverse order, so update this reverse bool value.
Should be reverted to older as --drop-useless-peers enabled, shouldn't not if not enable this flag
=> fix: Update params of request to match erigon request mechanism

cmd/rpcdaemon/commands/bsc_api.go, cmd/rpcdaemon/commands/daemon.go, core/types/block.go, node/rpcstack.go
BSC geth contains several RPC API calls under 'eth' namespace which are missed in Erigon. That means some issues are possible when you are trying to substitute BSC geth instance with Erigon instance, some services that use this API can be broken.
Full list of this RPC calls:
eth_getDiffAccountsWithScope
eth_getHeaderByHash
eth_getDiffAccounts
eth_getVerifyResult
eth_health
eth_getHeaderByNumber
eth_getTransactionsByBlockNumber
eth_resend
eth_fillTransaction
eth_getTransactionDataAndReceipt
eth_getTransactionReceiptsByBlockNumber
eth_pendingTransactions
eth_getHashrate
eth_etherbase
eth_subscribeSyncStatus
eth_getFilterLogs
Some of this calls are not implemented in original geth too, so this API set is optional, it is available only if user adds bsc entity to -http.api parameter (i.e. …
=> Missed RPC calls implemented in BSC geth

.gitignore, consensus/parlia/parlia.go, core/state/intra_block_state.go, core/state/state_object.go
Solve the mismatch validator bug with final solution:
Previously, sometimes "mismatching validator" error occur, after dive into more into the code, the root reason is that ibs(IntraBlockState) is not thread-safe, in evm system contract call, it'll read messy cache data.
With this commit, will create a new state for read validatorList to avoid messy cache data and thread-safe problem
=> fix: Solve the mismatch validator bug with final solution

params/version.go
Use the actual version of bsc-erigon fork
=> fix: Update the version for bsc-erigon

go.mod, go.sum, turbo/snapshotsync/snapcfg/util.go
Support torrent for bsc testnet
=> feat: Support torrent for bsc testnet

turbo/stages/headerdownload/header_algos.go
Fixed bad block hash because of chain reorg, due to badHeaders map wasn't updated once new fork imported
=> fix: fix bad block hash because of chain reorg

core/state/state_object.go
I think BSC will release a blog or something to reveal the detail of `Hertzfix`, will put the link here once ready.
=> fix: the patch for Hertzfix

cmd/hack/hack.go, cmd/state/commands/check_change_sets.go, core/state/access_list_test.go, core/state/database_test.go, core/state/intra_block_state_test.go, core/state/plain_readonly.go, core/state/state_test.go, core/state/temporal/kv_temporal.go, core/system_contract_lookup.go, core/vm/runtime/runtime_test.go, go.mod, go.sum, turbo/rpchelper/helper.go
Bsc use SystemContractCodeLookup to access code of such contracts instead of query from db. After Kepler hard fork, Bsc hard fork will transfer to blockTime.
=> Fix trace apis after Kepler hard fork.

core/state/plain_readonly.go
Erigon's history doesn't store "current state" in history. 
It stores prevValue, just State at the beginning of blockNr.
It means history of block N stores "what values we had before block N". 
So, to get value of addr A asOf block N, need find first appearance of A in history of blocks N+1.
The bug was introduced by this pr:https://github.com/node-real/bsc-erigon/pull/154.  This pr will revert this change
=> Fix the bug about trace api.

turbo/stages/headerdownload/header_algos.go
Just think one case:  now justifiedNum is 6.  The next blockheight is 8, have received 2 block and the first block justifiedNum is 7, and the second is 6. The first will be accept and the second will lost. But then unwind to the second block. The totalDifficult would be wrong.
Refer #293
=> write block totalDifficult anyway

core/data_availability.go, core/types/block.go, eth/stagedsync/stage_bodies.go, p2p/sentry/sentry_multi_client/broadcast.go, p2p/sentry/sentry_multi_client/sentry_multi_client.go, params/version.go, turbo/stages/bodydownload/body_algos.go
Fix the sidecar boardcast issue #387
=> Fix sidecar boardcast issue

core/data_availability.go, eth/stagedsync/stage_bodies.go, p2p/sentry/sentry_multi_client/sentry_multi_client.go, turbo/stages/bodydownload/body_data_struct.go
Fix #431 , the problem about blob sidecar miss match
After upstream the latest erigon code. The default check dataAbility logic broken because of `--sync.loop.block.limit`. So add a mark when received new block.
=> add a mark for latest block

cmd/state/exec3/state.go, erigon-lib/go.mod, erigon-lib/go.sum, go.mod, go.sum, params/version.go
1. prepare release erigon3 for chapel
2. don't get parent block time. It waste too much time to query parent.time before exec the tx.
=> Release erigon3 alpha1

params/version.go
Bump version. v1.3.0-alpha is correspond erigontech/erigon v3.0.0-alpha1
=> bump version

README.md, cmd/state/exec3/state.go, consensus/aura/auraabi/gen_block_reward.go, consensus/misc/eip4844.go, consensus/parlia/feynmanfork.go, consensus/parlia/parlia.go, core/vm/contracts_lightclient.go, core/vm/lightclient/iavl/proof.go, core/vm/lightclient/v2/lightclient.go, eth/protocols/eth/protocol_test.go, turbo/stages/headerdownload/header_algos.go
**Done**
1. fix go lint 
2. fix unit test
3. update readme with erigon3 data info
**Todo**
fix the integration test
=> Update readme and fix ci

Makefile, go.mod, go.sum, wmake.ps1
1. fix build binary warn: 'ld: warning: ignoring duplicate libraries: '-lc++''
2. remove build tag "netgo".
=> fix ld: warning: ignoring duplicate libraries: '-lc++'

consensus/parlia/parlia.go, core/state_transition.go
Fix #522 , get system transaction receipt should skip gas check.  In erigon3 need to execute tx to get receipt, so remove st.evm.Config().Debug check, and add gasprice check.
=> Fix eth_getTransactionReceipts

cmd/state/commands/opcode_tracer.go, core/blockchain.go, core/chain_makers.go, turbo/jsonrpc/trace_filtering.go
Fix trace_* api crash.
`[EROR] [10-22|02:55:01.182] RPC method trace_transaction crashed: runtime error: invalid memory address or nil pointer dereference
[service.go:223 panic.go:770 panic.go:261 signal_unix.go:881 parlia.go:913 blockchain.go:506 trace_filtering.go:778 trace_filtering.go:124 value.go:596 value.go:380 service.go:228 handler.go:534 handler.go:484 handler.go:425 handler.go:245 handler.go:338 asm_amd64.s:1695] `
=> Fix trace_* api

cmd/integration/commands/stages.go, eth/backend.go, eth/ethconfig/config.go, eth/ethconsensusconfig/config.go, turbo/app/snapshots_cmd.go, turbo/cli/default_flags.go, turbo/cli/flags.go, turbo/snapshotsync/snapshotsync.go, turbo/stages/stageloop.go
Seem blob info are useless, so don't keep all the blob info by default.  Add `bsc.blobSidecars.no-pruning=true` to keep all blobs.
=> default not keep all blob info.

core/genesis_write.go, core/state/rw_v3.go, erigon-lib/state/aggregator.go, erigon-lib/state/domain_shared.go, eth/stagedsync/exec3.go
Add a new mode: sync without check state root. It will save disk usage(300gb in bsc) add have higher speed.
How to enable:
1. remove all the commitment 
```
./erigon seg rm-state --domain=commitment --datadir=./data
rm -rf datadir/chaindata
```
2. restart with env flag ` ERIGON_DISCARD_COMMITMENT=true` 
Attention: If enable this mode can't switch back to the default mode. (Need resync)
=> experiment: a new sync mode with `DISCARD_COMMITMENT`

README.md, cl/clparams/config.go, cmd/caplin/caplin1/run.go, consensus/aura/aura.go, consensus/clique/clique.go, core/forkid/forkid_test.go, erigon-lib/commitment/commitment.go, erigon-lib/commitment/commitment_bench_test.go, erigon-lib/commitment/commitment_test.go, erigon-lib/commitment/hex_patricia_hashed.go, erigon-lib/commitment/hex_patricia_hashed_bench_test.go, erigon-lib/commitment/hex_patricia_hashed_fuzz_test.go, erigon-lib/commitment/hex_patricia_hashed_test.go, erigon-lib/commitment/patricia_state_mock_test.go, erigon-lib/state/domain_shared.go, erigon-lib/state/domain_shared_test.go, eth/stagedsync/stage_mining_exec.go, params/chainspecs/holesky.json, params/chainspecs/sepolia.json, polygon/heimdall/client_http.go, turbo/jsonrpc/eth_receipts.go, turbo/snapshotsync/caplin_state_snapshots.go, turbo/snapshotsync/snapshots.go
Pick.  [Revert](https://github.com/node-real/bsc-erigon/commit/3e9aea6ec1662a100d6035a5a4e3eb5da1cd12e8) https://github.com/erigontech/erigon/pull/13509 ["Commitment: do not use cell getter function …](https://github.com/node-real/bsc-erigon/commit/3e9aea6ec1662a100d6035a5a4e3eb5da1cd12e8)
=> Upstream for qa issue

erigon-lib/downloader/webseed.go
Fix no metadata yet issue in bsc-erigon
=> StageSnapshot struck: fix "no metadata yet"

eth/gasprice/feehistory.go, eth/gasprice/gasprice.go, turbo/jsonrpc/eth_receipts.go, turbo/jsonrpc/eth_system.go, turbo/jsonrpc/receipts/receipts_generator.go
Currently, a significant amount of time is spent on re-executing transactions. However, in reality, only the gasused by the transaction is needed, which can be obtained through the ` kv.ReceiptDomain`
After this pr, time from 117s -> 119ms
=> eth_feehistory: fix high latency feehistory

consensus/parlia/parlia.go
parlia.go: remove validateHeaderUnusedFields, both checked in verifyHeader.
=> parlia.go: remove MixDigest check in validateHeaderUnusedFields.

params/chainspecs/bsc.json, params/chainspecs/chapel.json, params/chainspecs/rialto.json
If blobSchedule is nil, it will use default `5007716` as baseFeeUpdateFraction after prague.
=> params/chainspecs: Add blob schedule to bsc and chapel

erigon-lib/chain/snapcfg/util.go
fix upstream issue, bsc-erigon-sanpshots use main branch as default. Fix #653 #650
=> util.go: change default DefaultSnapshotGitBranch to main

cmd/state/exec3/state.go, consensus/parlia/parlia.go
If there are no`useTxs`,but distributing the `FinalityReward`and updating the validator set with`updateValidatorSetV2`is necessary,the logic for updating`curIndex`would be flawed.Additionally,the`updateValidatorSetV2`transaction is expected to trigger the`distributeFinalityReward` function.
=> parlia.go: add check for distributeToValidator

turbo/snapshotsync/freezeblocks/block_reader.go
Fix handle message panic
`
[DBUG] [05-20|02:45:30.567] Handling incoming message                stream=RecvUploadMessage err="runtime error: invalid memory address or nil pointer dereference, msgID=GET_BLOCK_BODIES_66, trace: [sentry_multi_client.go:648 panic.go:770 panic.go:261 signal_unix.go:881 block_reader.go:762 handlers.go:152 sentry_multi_client.go:558 sentry_multi_client.go:682 sentry_multi_client.go:651 loop.go:126 asm_amd64.s:1695]"
`
=> block_reader.go: fix panic

eth/stagedsync/stage_headers.go, turbo/stages/headerdownload/header_algos.go, turbo/stages/headerdownload/header_data_struct.go
We should reduce the frequency of requesting skeletons when the node is at the chain tip.
=> stage_headers.go: reduce skeleton request frequency

erigon-lib/config3/config3.go
During live sync, the table ChangeSet size tends to grow（more than 100GB） because there isn't sufficient time to pruning, which negatively impacts performance and causes the db size to increase significantly. However, in BSC, we experience infrequent reorganizations (< 2block) due to fast-finality consensus. Therefore, we've reduced MaxReorgDepthV3 to 8 to enable more aggressive pruning and maintain optimal database performance
=> config3.go: reduce MaxReorgDepthV3 to have more aggressive prune

turbo/stages/headerdownload/header_algos.go
=> header_algos.go: fix goroutine race

eth/stagedsync/stage_bodies.go, eth/stagedsync/stage_snapshots.go, turbo/snapshotsync/freezeblocks/block_snapshots.go, turbo/snapshotsync/freezeblocks/bsc_snapshots.go, turbo/stages/headerdownload/header_algos.go
Fix: #732 
1. stage_snapshots.go: adjust `pruneMarkerSafeThreshold` to keep the `HeaderCanonical` until blob snapshots generate
2. header_algos.go: add writeCanonicalHash when import header
3. bsc_snapshots.go: optimize bsc_snapshots
4. stage_bodies.go: clean cache when received empty blob.
=> bsc_snapshots.go: fix bsc snapshots

erigon-lib/config3/config3.go, eth/stagedsync/stage_execute.go
1. in chapel, the chain may unwind more than 100 block, so it need bigger in chapel. fix #745
=> stage_execute.go: fix unwind issues

erigon-lib/config3/config3.go, eth/stagedsync/exec3.go, eth/stagedsync/stage_execute.go
```
Table                       Branch     Leaf Overflow    Entries Total(MB)    Ovfl%    Depth
-------------------------------------------------------------------------------------
open-MADV_DONTNEED 16928767..16928768
readahead OFF 0..16928768
1        3       94         97     0.38    95.9%        2
BlockTransaction               350    77559    24228     715227   398.97    23.7%        4
ChangeSets3                   2385   164305 10449963   10482482 41471.30    98.4%        4
CodeVals                         1       84      649       1605     2.87    88.4%        2
Config                           0        1     1067          2     4.17    99.9%        1
Header                          19     1288        5       5152     5.12     0.4%        3
TxSender                         4 …
```
=> exec3.go: decrease changesetSafeRange
